### ISSUE TITLE
Unify Windows and Unix key generations

### ISSUE THREAD

**Issue by nopjmp** [keybase/bot-sshca#27]
It looks like ssh is already a requirement for parts of keybaseca and was wondering why the key generation is split where Windows uses crypto/ssh for it's RSA keys and Unix uses ed25519 via ssh-keygen.

Requirement here:
https://github.com/keybase/bot-sshca/blob/4682fde9f29dca1e95052395802d30117c15d5b5/src/keybaseca/sshutils/sshutils.go#L122-L129

**Comment by aditsachde** [comment]
They explained their design choice [in the readme](https://github.com/keybase/bot-sshca#ssh-operations)

>On nix style systems (linux and MacOS), kssh generates and uses ed25519 private keys using the ssh-keygen binary. In order to remove the dependency on ssh-keygen for windows systems (since it is not always installed on windows), kssh will generate a 2048 bit RSA key when running on Windows.

**Comment by ddworken** [comment]
Yup exactly what @aditsachde said! There are two parts to this system. Keybaseca is the server side component and it is only supported to run this on Linux (and we recommend running it on Linux inside of docker, see `docker/`). Kssh is the client side component and is meant to work on Windows, Mac, and Linux. Because of this, we avoid depending on ssh-keygen on Windows.

**Comment by nopjmp** [comment]
I see, I didn't look through all of the dependencies, i just noticed it inside of the keybaseca resource which makes sense.

I'll close the issue now :)

**Comment by ddworken** [comment]
@nopjmp Just wanted to let you know that in #36 I migrated the ssh key generation to be pure go and thus remove the dependency on ssh-keygen. Thus, all generated SSH keys are now ed25519 keys! :)
