### ISSUE TITLE
[Bug] Key names miss uniqueness.

### ISSUE THREAD

**Issue by Johannestegner** [keybase/bot-sshca#48]
All generated SSH keys seems to get the same name (`keybase-signed-key--`) making them not-unique. Maybe they should contain the name of the team or just use some type of hash of the team name instead?

**Comment by ddworken** [comment]
Is there a reason you want the names to be unique? What currently happens is that whenever a new key is generated (likely because the previous one expired) it overwrites the expired one. Is there a use case I'm missing for keeping the expired keys around?

And for what it is worth, the way multi-team support is implemented (eg you have an SSH CA bot for work and one for personal usage) does do exactly what you suggest: It places the specified bot name in the filename: 

https://github.com/keybase/bot-sshca/blob/master/src/cmd/kssh/kssh.go#L85-L95

**Comment by Johannestegner** [comment]
No you are right, it's just me that failed to think straight!
Thanks for clarification, I'll close this issue :)
